# public API

### instantiation of exchange

In [2]:
import pandas as pd
import numpy as np
import ccxt

In [3]:
exchange = ccxt.binanceusdm({
	'apiKey': '',
	'secret': '',
})
# turn on testnet
# hasattr(exchange, 'set_sandbox_mode')
exchange.set_sandbox_mode(True)

In [4]:
exchange.timeframes

{'1s': '1s',
 '1m': '1m',
 '3m': '3m',
 '5m': '5m',
 '15m': '15m',
 '30m': '30m',
 '1h': '1h',
 '2h': '2h',
 '4h': '4h',
 '6h': '6h',
 '8h': '8h',
 '12h': '12h',
 '1d': '1d',
 '3d': '3d',
 '1w': '1w',
 '1M': '1M'}

In [4]:
exchange.fetch_ticker(symbol='ETHUSDT')

{'symbol': 'ETH/USDT',
 'timestamp': 1759191235120,
 'datetime': '2025-09-30T00:13:55.120Z',
 'high': 4230.28,
 'low': 4077.0,
 'bid': None,
 'bidVolume': None,
 'ask': None,
 'askVolume': None,
 'vwap': 4170.47,
 'open': 4135.9,
 'close': 4220.39,
 'last': 4220.39,
 'previousClose': None,
 'change': 84.49,
 'percentage': 2.043,
 'average': 4178.145,
 'baseVolume': 390597.043,
 'quoteVolume': 1628974749.37,
 'info': {'symbol': 'ETHUSDT',
  'priceChange': '84.49',
  'priceChangePercent': '2.043',
  'weightedAvgPrice': '4170.47',
  'lastPrice': '4220.39',
  'lastQty': '0.007',
  'openPrice': '4135.90',
  'highPrice': '4230.28',
  'lowPrice': '4077.00',
  'volume': '390597.043',
  'quoteVolume': '1628974749.37',
  'openTime': '1759104780000',
  'closeTime': '1759191235120',
  'firstId': '188422841',
  'lastId': '188526948',
  'count': '104093'}}

In [6]:
df = pd.DataFrame(exchange.fetch_ohlcv(symbol='ETHUSDT', timeframe='4h', limit= 1000))

In [7]:
df.describe()

,0,1,2,3,4,5
count,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,1.751998e+12,3170.437850,3353.721740,3072.371180,3173.712570,2.461876e+05
std,4.159000e+09,968.591289,3351.365367,949.870947,967.776232,5.873907e+05
min,1.744805e+12,1560.000000,1574.980000,1430.000000,1559.570000,0.000000e+00
25%,1.748401e+12,2475.762500,2529.867500,2390.000000,2479.860000,4.351428e+04
50%,1.751998e+12,2770.765000,2835.000000,2647.925000,2772.725000,1.151504e+05
75%,1.755594e+12,4174.912500,4250.000000,4017.642500,4178.277500,2.352047e+05
max,1.759190e+12,4806.190000,104454.900000,4660.000000,4799.990000,5.988052e+06

### get data && clean data

In [8]:
exchange.rateLimit/1000

0.05

In [9]:
import time


def get_history(symbol, interval, start= None, limit = 1000):
	if start:
		start = exchange.parse8601(start)

	data = exchange.fetch_ohlcv(symbol=symbol, timeframe=interval, since=start, limit=limit) 
	lastBarActual = data[-1][0] # timestamp of last loaded bar
	# timestamp of current bar
	lastBarCurrent = exchange.fetch_ohlcv(symbol=symbol, timeframe=interval, limit=1)[-1][0]
	# if lastBarActual != lastBarCurrent => pull the next 1000 bars
	while lastBarActual != lastBarCurrent:
		time.sleep(0.1)
		data += exchange.fetch_ohlcv(symbol=symbol, timeframe=interval, since=lastBarActual, limit=limit)[1:]
		lastBarActual = data[-1][0]
		lastBarCurrent = exchange.fetch_ohlcv(symbol=symbol, timeframe=interval, limit=1)[-1][0]

	df = pd.DataFrame(data)
	df.columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']
	df.Date= pd.to_datetime(df.Date, unit='ms')
	df.set_index('Date', inplace=True)
	
	return df

In [10]:
start = "2022-01-01 00:00:00"
# since start but max 1000 bars
df = get_history('ETHUSDT', '2h', start=start, limit=1000)
df.info

KeyboardInterrupt:

In [18]:
df.index.is_unique

True

## streaming data

In [20]:
# basic idea to streaming klines with no requirement for low latency
for i in range(10):
    data = exchange.fetch_ohlcv(symbol='ETHUSDT', timeframe='2h', limit= 1)
    print(data)
    time.sleep(1)

[[1679198400000, 1763.19, 1777.46, 1761.08, 1776.72, 1478.979]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1479.73]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1479.73]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1479.73]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1479.73]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1479.73]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1479.73]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1479.73]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1480.045]]
[[1679198400000, 1763.19, 1777.46, 1761.08, 1777.46, 1480.045]]

In [20]:
def start_klines(callback, symbol, interval):
	global running # global variable to control the loop externally
	running = True
 
	while running == True:
		res = exchange.fetch_ohlcv(symbol=symbol, timeframe=interval, limit= 1)
		if len(res) == 0:
			print('no data')
		else:
			callback(res)
		time.sleep(1)

In [13]:
df = pd.DataFrame(columns= ["Open", "High", "Low", "Close", "Volume"])
df

Empty DataFrame
Columns: [Open, High, Low, Close, Volume]
Index: []

In [24]:
def stream_candles(res):
    # define how to process the data

    # extract data from res
    start_time = pd.to_datetime(res[0][0], unit='ms') # res:[[1679198400000, 1763.19, 1777.46, 1761.08, 1776.72, 1478.979]]
    first = res[0][1]
    high = res[0][2]
    low = res[0][3]
    close = res[0][4]
    volume = res[0][5]

    # feed the df
    df.loc[start_time] = [first, high, low, close, volume]

    # print sth
    print(".", end = "", flush = True)

In [6]:
def stop_stream():
	global running
	running = False

### multithreading

In [8]:
from threading import Thread

In [25]:
thread = Thread(target=start_klines, args=(stream_candles, 'ETHUSDT', '1m'))
thread

In [26]:
thread.start()

....................

In [27]:
stop_stream()

In [15]:
thread

In [16]:
thread.start()

[[1679293020000, 1749.95, 1751.0, 1749.95, 1751.0, 36.759]]
[[1679293020000, 1749.95, 1751.0, 1749.95, 1749.95, 36.988]]
[[1679293020000, 1749.95, 1751.0, 1749.95, 1749.95, 36.988]]
[[1679293020000, 1749.95, 1751.0, 1749.95, 1749.95, 36.988]]
[[1679293020000, 1749.95, 1751.0, 1749.95, 1749.95, 36.988]]
[[1679293020000, 1749.95, 1751.0, 1749.95, 1749.95, 36.988]]
[[1679293020000, 1749.95, 1751.0, 1749.95, 1751.0, 37.217]]

In [17]:
stop_stream()

[[1679293080000, 1751.0, 1751.0, 1749.95, 1749.95, 57.732]]

In [28]:
df

                       Open    High      Low    Close  Volume
2023-03-20 06:19:00  1751.0  1751.0  1749.95  1750.98  95.629
2023-03-20 06:20:00  1751.0  1751.0  1750.98  1750.98   1.775