In [1]:
import pandas as pd
import talib.abstract as ta
import numpy as np

In [8]:
df = pd.read_csv('bitcoin.csv')
tdf = df.tail(1000)
tdf.tail(100)

                      Date      Open      High       Low     Close      Volume
36068  2021-10-03 06:00:00  47990.13  48057.00  47896.93  47972.99   617.25174
36069  2021-10-03 07:00:00  47970.15  47970.16  47814.00  47895.99   569.31948
36070  2021-10-03 08:00:00  47896.00  47983.38  47798.50  47823.99   838.17079
36071  2021-10-03 09:00:00  47823.98  47869.00  47600.00  47830.09  1489.72226
36072  2021-10-03 10:00:00  47830.09  47953.20  47730.00  47812.32   625.24084
...                    ...       ...       ...       ...       ...         ...
36163  2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.12202
36164  2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.00426
36165  2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.43136
36166  2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.38218
36167  2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.15361

[100 rows x 6 columns]

In [9]:
tdf.columns=[col.lower() for col in tdf.columns]
tdf

                      date      open      high       low     close      volume
35168  2021-08-26 16:00:00  46800.00  47056.86  46485.16  46897.72  2263.61921
35169  2021-08-26 17:00:00  46897.72  47123.65  46886.01  46950.26  1276.36545
35170  2021-08-26 18:00:00  46950.26  47092.63  46731.00  47001.46  1128.54621
35171  2021-08-26 19:00:00  47001.47  47043.88  46755.27  46939.75  1212.66545
35172  2021-08-26 20:00:00  46934.22  47058.23  46845.00  47017.57   949.73043
...                    ...       ...       ...       ...       ...         ...
36163  2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.12202
36164  2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.00426
36165  2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.43136
36166  2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.38218
36167  2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.15361

[1000 rows x 6 columns]

In [17]:
def regression_ema(dataframe:pd.DataFrame, timeperiod=144) -> pd.Series:
    df = dataframe.copy()
    # get deviation
    df['cline'] = ta.MA(dataframe, 50)
    df['deviation'] = (df['close']-df['cline']) 
    # get percentile
    df['bull_quantile'] = df['deviation'].mask(df['deviation'] < 0).rolling(window=timeperiod).quantile(0.6)
    df['bear_quantile'] = df['deviation'].mask(df['deviation'] > 0).rolling(window=timeperiod).quantile(0.4)
    # df['pass_reg_filter'] = np.where(
    #     df['deviation'].between(df['bull_quantile'], df['bear_quantile']), 1, 0)
    df['pass_reg_filter'] = np.where(
        ~pd.isna(df['deviation']),
        np.where(
        df['deviation'] > df['bull_quantile'], -1, 
        np.where((df['deviation'] < df['bear_quantile']), 1, 0)),
        np.nan
        )
    return df[['deviation','bull_quantile', 'bear_quantile', 'pass_reg_filter']]

In [19]:
tdf[['deviation', 'bull_quantile', 'bear_quantile', 'pass_reg_filter']] = regression_ema(tdf, 21)

C:\Users\xlfin\AppData\Local\Temp\ipykernel_12964\3930854815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tdf[['deviation', 'bull_quantile', 'bear_quantile', 'pass_reg_filter']] = regression_ema(tdf, 21)
C:\Users\xlfin\AppData\Local\Temp\ipykernel_12964\3930854815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tdf[['deviation', 'bull_quantile', 'bear_quantile', 'pass_reg_filter']] = regression_ema(tdf, 21)
C:\Users\xlfin\AppData\Local\Temp\ipykernel_12964\3930854815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tdf[['deviation', 'bull_quantile', 'bear_quantile', 'pass_reg_filter']] = regression_ema(tdf, 21)
C:\Users\xlfin\AppData\Local\Temp\ipykernel_12964\3930854815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tdf[['deviation', 'bull_quantile', 'bear_quantile', 'pass_reg_filter']] = regression_ema(tdf, 21)

In [21]:
tdf.tail(50)

,date,open,high,low,close,volume,deviation,bull_quantile,bear_quantile,pass_reg_filter
36118,2021-10-05 08:00:00,49476.52,50000.00,49376.06,49919.99,2544.685460,-80.01,NaN,-831.69,0.0
36119,2021-10-05 09:00:00,49920.00,50328.00,49584.40,50269.35,3724.600840,269.35,NaN,NaN,0.0
36120,2021-10-05 10:00:00,50269.35,50350.00,49839.26,49999.99,2413.651530,-0.01,NaN,NaN,0.0
36121,2021-10-05 11:00:00,49999.99,50145.88,49801.74,49877.06,1611.669930,-122.94,NaN,NaN,0.0
36122,2021-10-05 12:00:00,49877.06,50110.00,49705.00,50000.00,2161.324870,0.00,NaN,NaN,0.0
36123,2021-10-05 13:00:00,50000.00,50320.00,49772.63,50207.96,2108.424410,207.96,NaN,NaN,0.0
36124,2021-10-05 14:00:00,50207.96,50388.00,49575.94,49841.79,3331.248360,-158.21,NaN,NaN,0.0
36125,2021-10-05 15:00:00,49841.78,50205.21,49700.00,49793.57,2394.236910,-206.43,NaN,NaN,0.0
36126,2021-10-05 16:00:00,49793.57,50115.24,49640.36,50103.85,1616.066060,103.85,NaN,NaN,0.0
36127,2021-10-05 17:00:00,50103.86,50200.00,49950.00,50146.52,1496.736340,146.52,NaN,NaN,0.0
36128,2021-10-05 18:00:00,50146.51,50777.00,50140.01,50612.44,3172.360750,612.44,NaN,NaN,0.0
36129,2021-10-05 19:00:00,50612.45,51388.00,50557.89,51190.11,4096.424220,1190.11,NaN,NaN,0.0
36130,2021-10-05 20:00:00,51190.11,51773.76,51104.47,51462.29,3445.451090,1462.29,NaN,NaN,0.0
36131,2021-10-05 21:00:00,51461.16,51886.30,51299.06,51718.61,2892.917660,1718.61,NaN,NaN,0.0
36132,2021-10-05 22:00:00,51718.61,51775.42,51318.24,51349.86,1929.756600,1349.86,NaN,NaN,0.0
36133,2021-10-05 23:00:00,51349.85,51620.37,51343.06,51471.99,1331.887820,1471.99,NaN,NaN,0.0
36134,2021-10-06 00:00:00,51471.99,51539.30,51201.05,51321.61,1874.267820,1321.61,NaN,NaN,0.0
36135,2021-10-06 01:00:00,51322.98,51330.96,50917.73,51278.38,1731.789060,1278.38,NaN,NaN,0.0
36136,2021-10-06 02:00:00,51277.30,51591.82,51152.00,51545.56,1546.248440,1545.56,NaN,NaN,0.0
36137,2021-10-06 03:00:00,51545.56,51600.00,51295.32,51513.81,1716.306880,1513.81,NaN,NaN,0.0
36138,2021-10-06 04:00:00,51512.13,51593.52,51236.70,51325.83,1788.572970,1325.83,NaN,NaN,0.0
36139,2021-10-06 05:00:00,51325.82,51828.00,51200.56,51512.37,3845.981640,1512.37,NaN,NaN,0.0
36140,2021-10-06 06:00:00,51516.11,51736.11,51450.85,51509.98,1795.945490,1509.98,NaN,NaN,0.0
36141,2021-10-06 07:00:00,51509.97,51575.10,51088.00,51449.99,2514.708150,1449.99,NaN,NaN,0.0
36142,2021-10-06 08:00:00,51450.00,51500.00,50420.00,50693.51,4693.989210,693.51,NaN,NaN,0.0
36143,2021-10-06 09:00:00,50695.74,50822.00,50382.41,50700.00,3309.284380,700.00,NaN,NaN,0.0
36144,2021-10-06 10:00:00,50700.00,51478.00,50619.10,51160.35,3675.566410,1160.35,NaN,NaN,0.0
36145,2021-10-06 11:00:00,51160.35,51490.00,51091.30,51306.56,2864.515720,1306.56,NaN,NaN,0.0
36146,2021-10-06 12:00:00,51306.57,52829.00,51259.84,52741.68,7188.980390,2741.68,1449.99,NaN,-1.0
36147,2021-10-06 13:00:00,52741.68,55555.00,52610.20,53997.00,13067.382057,3997.00,1462.29,NaN,-1.0
36148,2021-10-06 14:00:00,53996.99,54550.00,53750.00,54500.40,4630.424800,4500.40,1471.99,NaN,-1.0
36149,2021-10-06 15:00:00,54500.40,55156.97,54250.04,54984.19,4393.701760,4984.19,1509.98,NaN,-1.0
36150,2021-10-06 16:00:00,54984.20,55054.87,54446.54,54891.32,3430.498620,4891.32,1512.37,NaN,-1.0
36151,2021-10-06 17:00:00,54891.32,54917.90,54517.01,54581.22,2185.694960,4581.22,1513.81,NaN,-1.0
36152,2021-10-06 18:00:00,54582.09,55109.67,54446.54,54527.82,2983.472340,4527.82,1513.81,NaN,-1.0
36153,2021-10-06 19:00:00,54527.82,55078.01,54483.85,55049.99,2056.358740,5049.99,1545.56,NaN,-1.0
36154,2021-10-06 20:00:00,55049.99,55386.86,54812.00,54918.24,2562.022010,4918.24,2741.68,NaN,-1.0
36155,2021-10-06 21:00:00,54918.24,55273.83,54880.05,55075.37,1617.265880,5075.37,3997.00,NaN,-1.0
36156,2021-10-06 22:00:00,55075.38,55280.00,54893.02,55144.72,1516.958190,5144.72,4500.40,NaN,-1.0
36157,2021-10-06 23:00:00,55144.72,55750.00,55119.08,55315.00,2887.609264,5315.00,4527.82,NaN,-1.0
36158,2021-10-07 00:00:00,55315.00,55332.31,54500.00,54794.88,3291.494880,4794.88,4581.22,NaN,-1.0
36159,2021-10-07 01:00:00,54794.88,54909.19,54112.00,54787.30,2806.591760,4787.30,4787.30,NaN,0.0
36160,2021-10-07 02:00:00,54787.30,55230.60,54680.92,55075.56,1938.382900,5075.56,4794.88,NaN,-1.0
36161,2021-10-07 03:00:00,55075.57,55215.67,54730.86,54810.94,1540.734810,4810.94,4810.94,NaN,0.0
36162,2021-10-07 04:00:00,54810.93,55237.04,54756.06,55073.20,1450.003900,5073.20,4891.32,NaN,-1.0
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.122020,4735.76,4891.32,NaN,0.0
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.004260,4534.16,4891.32,NaN,0.0
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.431360,4755.92,4891.32,NaN,0.0
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.382180,4538.30,4891.32,NaN,0.0
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.153610,3995.50,4891.32,NaN,0.0