In [1]:
import pandas as pd

In [2]:
import numpy as np
import talib.abstract as ta

In [3]:
test = pd.read_csv('bitcoin.csv')
test = test.tail(100)
test

                      Date      Open      High       Low     Close      Volume
36068  2021-10-03 06:00:00  47990.13  48057.00  47896.93  47972.99   617.25174
36069  2021-10-03 07:00:00  47970.15  47970.16  47814.00  47895.99   569.31948
36070  2021-10-03 08:00:00  47896.00  47983.38  47798.50  47823.99   838.17079
36071  2021-10-03 09:00:00  47823.98  47869.00  47600.00  47830.09  1489.72226
36072  2021-10-03 10:00:00  47830.09  47953.20  47730.00  47812.32   625.24084
...                    ...       ...       ...       ...       ...         ...
36163  2021-10-07 05:00:00  55073.20  55073.21  54545.07  54735.76  2251.12202
36164  2021-10-07 06:00:00  54735.77  54968.06  54375.83  54534.16  1783.00426
36165  2021-10-07 07:00:00  54534.16  54793.26  54235.33  54755.92  4163.43136
36166  2021-10-07 08:00:00  54755.91  54778.91  54400.00  54538.30  2049.38218
36167  2021-10-07 09:00:00  54538.31  54547.30  53786.13  53995.50  2739.15361

[100 rows x 6 columns]

In [4]:
slice = test.iloc[-14:]
slice

,Date,Open,High,Low,Close,Volume
36154,2021-10-06 20:00:00,55049.99,55386.86,54812.00,54918.24,2562.022010
36155,2021-10-06 21:00:00,54918.24,55273.83,54880.05,55075.37,1617.265880
36156,2021-10-06 22:00:00,55075.38,55280.00,54893.02,55144.72,1516.958190
36157,2021-10-06 23:00:00,55144.72,55750.00,55119.08,55315.00,2887.609264
36158,2021-10-07 00:00:00,55315.00,55332.31,54500.00,54794.88,3291.494880
36159,2021-10-07 01:00:00,54794.88,54909.19,54112.00,54787.30,2806.591760
36160,2021-10-07 02:00:00,54787.30,55230.60,54680.92,55075.56,1938.382900
36161,2021-10-07 03:00:00,55075.57,55215.67,54730.86,54810.94,1540.734810
36162,2021-10-07 04:00:00,54810.93,55237.04,54756.06,55073.20,1450.003900
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.122020
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.004260
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.431360
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.382180
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.153610